"""Add phone and salary to doctors

Revision ID: f5f07de3fb6c
Revises: 62b946d6ba8a
Create Date: 2026-07-12 14:02:49.444847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f07de3fb6c'
down_revision: Union[str, Sequence[str], None] = '62b946d6ba8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('doctors', sa.Column('salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'salary')
    op.drop_column('doctors', 'phone')
    # ### end Alembic commands ###
